import { useNavigate } from 'react-router-dom';

/**
 * Renders a view document produced by an installed app (APP-VIEW-001 §2).
 *
 * The app never sends markup — it sends a description of blocks, and this file
 * is the only thing that turns that description into a screen. That is the
 * whole security model: app code is generated by a language model, so if it
 * could reach the DOM we would be pasting untrusted markup into our own origin.
 * Anything unrecognised here renders as nothing rather than as raw text.
 */

export type EntityRef = { entity: 'job' | 'lead' | 'contact' | 'invoice' | 'estimate'; id: number | string; label?: string };

export type ViewValue =
    | string
    | number
    | null
    | { type: 'badge'; text: string; tone?: Tone }
    | { type: 'entity'; ref: EntityRef };

export type Tone = 'neutral' | 'accent' | 'success' | 'danger';

export type ViewBlock =
    | { type: 'stat_row'; items: { label: string; value: string; tone?: Tone; trend?: string }[] }
    | { type: 'chart'; chart: 'bar' | 'line'; series: { label: string; value: number }[]; format?: 'number' | 'currency' }
    | { type: 'table'; title?: string; columns: { key: string; label: string; align?: 'left' | 'right' }[]; rows: Record<string, ViewValue>[] }
    | { type: 'list'; title?: string; items: { title: string; subtitle?: string; badge?: { text: string; tone?: Tone }; ref?: EntityRef }[] }
    | { type: 'text'; text: string }
    | { type: 'empty'; text: string };

export interface ViewDocument {
    view_version: number;
    title?: string;
    subtitle?: string;
    blocks: ViewBlock[];
}

const ENTITY_ROUTES: Record<EntityRef['entity'], string> = {
    job: '/jobs',
    lead: '/leads',
    contact: '/contacts',
    invoice: '/invoices',
    estimate: '/estimates',
};

function toneColor(tone?: Tone): string {
    if (tone === 'danger') return 'var(--blanc-danger)';
    if (tone === 'success') return 'var(--blanc-success)';
    if (tone === 'accent') return 'var(--blanc-accent)';
    return 'var(--blanc-ink-1)';
}

function Badge({ text, tone }: { text: string; tone?: Tone }) {
    const danger = tone === 'danger';
    return (
        <span
            className="inline-block whitespace-nowrap rounded-full px-2 py-0.5 text-[11px] font-semibold"
            style={{
                background: danger ? 'rgba(240, 80, 63, 0.12)' : 'var(--blanc-accent-soft)',
                color: danger ? 'var(--blanc-danger)' : 'var(--blanc-accent)',
            }}
        >
            {text}
        </span>
    );
}

function EntityLink({ entity, id, label }: EntityRef) {
    const navigate = useNavigate();
    const route = ENTITY_ROUTES[entity];
    if (!route) return <span>{label || String(id)}</span>;
    return (
        <button
            type="button"
            onClick={() => navigate(`${route}/${id}`)}
            className="font-semibold hover:underline"
            style={{ color: 'var(--blanc-accent)' }}
        >
            {label || String(id)}
        </button>
    );
}

function Cell({ value }: { value: ViewValue }) {
    if (value === null || value === undefined) return null;
    if (typeof value === 'string' || typeof value === 'number') return <>{value}</>;
    if (value.type === 'badge') return <Badge text={value.text} tone={value.tone} />;
    if (value.type === 'entity') return <EntityLink {...value.ref} />;
    return null;
}

function StatRow({ block }: { block: Extract<ViewBlock, { type: 'stat_row' }> }) {
    return (
        <div className="grid gap-2.5" style={{ gridTemplateColumns: `repeat(${Math.min(block.items.length, 4)}, minmax(0, 1fr))` }}>
            {block.items.slice(0, 4).map((item, index) => (
                <div key={index} className="rounded-2xl px-3.5 py-3" style={{ background: 'var(--blanc-surface-muted)' }}>
                    <div
                        className="text-[23px] font-semibold tabular-nums tracking-tight"
                        style={{ color: toneColor(item.tone) }}
                    >
                        {item.value}
                    </div>
                    <div className="mt-0.5 text-xs" style={{ color: 'var(--blanc-ink-2)' }}>{item.label}</div>
                    {item.trend && (
                        <div className="mt-1.5 text-[11.5px]" style={{ color: 'var(--blanc-ink-3)' }}>{item.trend}</div>
                    )}
                </div>
            ))}
        </div>
    );
}

function Chart({ block }: { block: Extract<ViewBlock, { type: 'chart' }> }) {
    const series = block.series.slice(0, 24);
    const peak = Math.max(...series.map(point => Math.abs(point.value)), 1);
    const format = (value: number) => (
        block.format === 'currency'
            ? `$${Math.round(value).toLocaleString('en-US')}`
            : value.toLocaleString('en-US')
    );
    return (
        <div className="flex h-[148px] items-end gap-2.5">
            {series.map((point, index) => (
                <div key={index} className="flex h-full flex-1 flex-col items-center justify-end gap-1.5">
                    <span className="text-[11.5px] tabular-nums" style={{ color: 'var(--blanc-ink-2)' }}>
                        {format(point.value)}
                    </span>
                    <div
                        className="w-full rounded-t-[10px] rounded-b-md"
                        style={{
                            height: `${Math.max((Math.abs(point.value) / peak) * 100, 3)}%`,
                            background: index < 2 ? 'var(--blanc-accent)' : 'var(--blanc-accent-soft)',
                        }}
                    />
                    <span className="max-w-full truncate text-[11.5px]" style={{ color: 'var(--blanc-ink-3)' }}>
                        {point.label}
                    </span>
                </div>
            ))}
        </div>
    );
}

function Table({ block }: { block: Extract<ViewBlock, { type: 'table' }> }) {
    const columns = block.columns.slice(0, 20);
    return (
        <div className="overflow-x-auto">
            <table className="w-full border-collapse text-[13.5px]">
                <thead>
                    <tr>
                        {columns.map(column => (
                            <th
                                key={column.key}
                                className={`blanc-eyebrow pb-2.5 pr-2.5 ${column.align === 'right' ? 'text-right pr-0' : 'text-left'}`}
                            >
                                {column.label}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody>
                    {block.rows.slice(0, 500).map((row, rowIndex) => (
                        <tr key={rowIndex}>
                            {columns.map(column => (
                                <td
                                    key={column.key}
                                    className={`py-2.5 pr-2.5 align-top ${column.align === 'right' ? 'pr-0 text-right font-semibold tabular-nums' : ''}`}
                                    style={rowIndex > 0 ? { borderTop: '1px solid var(--blanc-line)' } : undefined}
                                >
                                    <Cell value={row[column.key]} />
                                </td>
                            ))}
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
}

function List({ block }: { block: Extract<ViewBlock, { type: 'list' }> }) {
    return (
        <div className="space-y-2">
            {block.items.map((item, index) => (
                <div
                    key={index}
                    className="flex items-center gap-3.5 rounded-xl px-3.5 py-3"
                    style={{ border: '1px solid var(--blanc-line)' }}
                >
                    <div className="min-w-0">
                        <div className="truncate font-medium">
                            {item.ref ? <EntityLink {...item.ref} /> : item.title}
                            {item.ref && item.title ? <span className="ml-1.5">{item.title}</span> : null}
                        </div>
                        {item.subtitle && (
                            <div className="mt-0.5 truncate text-[12.5px]" style={{ color: 'var(--blanc-ink-2)' }}>
                                {item.subtitle}
                            </div>
                        )}
                    </div>
                    {item.badge && <span className="ml-auto"><Badge text={item.badge.text} tone={item.badge.tone} /></span>}
                </div>
            ))}
        </div>
    );
}

function Block({ block }: { block: ViewBlock }) {
    const title = 'title' in block && block.title ? block.title : null;
    let body: React.ReactNode = null;
    if (block.type === 'stat_row') body = <StatRow block={block} />;
    else if (block.type === 'chart') body = <Chart block={block} />;
    else if (block.type === 'table') body = <Table block={block} />;
    else if (block.type === 'list') body = <List block={block} />;
    else if (block.type === 'text') {
        body = <p className="text-sm leading-6" style={{ color: 'var(--blanc-ink-2)' }}>{block.text}</p>;
    } else if (block.type === 'empty') {
        body = (
            <div className="rounded-2xl px-4 py-6 text-center text-sm" style={{ background: 'var(--blanc-surface-muted)', color: 'var(--blanc-ink-2)' }}>
                {block.text}
            </div>
        );
    } else {
        // An unknown block means the app targets a newer view version than this
        // build renders. Showing nothing is correct; showing raw JSON is not.
        return null;
    }
    return (
        <div>
            {title && <div className="blanc-eyebrow mb-3">{title}</div>}
            {body}
        </div>
    );
}

export function AppViewDocument({ document }: { document: ViewDocument }) {
    if (!document?.blocks?.length) {
        return (
            <div className="rounded-2xl px-4 py-6 text-center text-sm" style={{ background: 'var(--blanc-surface-muted)', color: 'var(--blanc-ink-2)' }}>
                This app returned nothing to show.
            </div>
        );
    }
    return (
        <div className="space-y-6">
            {document.blocks.slice(0, 64).map((block, index) => <Block key={index} block={block} />)}
        </div>
    );
}
