'use strict';

/**
 * Shared document-email wrapper. Existing invoice callers pass operator copy;
 * server-rendered document emails may opt into preformatted, already-escaped
 * HTML while retaining the same outer email seam.
 */
function buildEmailBody(message, link, { preformatted = false } = {}) {
    const content = preformatted
        ? String(message || '')
        : String(message || '').replace(/\r\n|\r|\n/g, '<br>');
    const anchor = link ? `<p><a href="${link}">View &amp; pay your invoice online</a></p>` : '';
    return `<div>${content}</div>${anchor}`;
}

function escapeHtml(value) {
    return String(value ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

function money(value) {
    const amount = Number(value || 0);
    const safeAmount = Number.isFinite(amount) ? amount : 0;
    return '$' + safeAmount.toLocaleString('en-US', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
    });
}

function formatDate(value, timeZone = 'America/New_York') {
    if (!value) return '';
    const raw = String(value);
    const dateOnly = raw.match(/^(\d{4})-(\d{2})-(\d{2})$/);
    if (dateOnly) {
        const [, year, month, day] = dateOnly;
        const monthName = new Intl.DateTimeFormat('en-US', { month: 'short', timeZone: 'UTC' })
            .format(new Date(Date.UTC(Number(year), Number(month) - 1, 1)));
        return `${monthName} ${Number(day)}, ${year}`;
    }

    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return '';
    try {
        return date.toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            year: 'numeric',
            timeZone: timeZone || 'America/New_York',
        });
    } catch {
        return date.toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            year: 'numeric',
            timeZone: 'America/New_York',
        });
    }
}

function factRow(label, value) {
    if (!value) return '';
    return `<tr>
        <td style="padding: 7px 0; color: #6F6F6B; font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-weight: bold; letter-spacing: 0.8px; text-transform: uppercase; vertical-align: top; width: 145px;">${escapeHtml(label)}</td>
        <td style="padding: 7px 0; color: #191919; font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-weight: bold; line-height: 20px; vertical-align: top;">${escapeHtml(value)}</td>
    </tr>`;
}

function totalRow(label, value, { strong = false, accent = false } = {}) {
    const color = accent ? '#7F42E1' : '#191919';
    const fontSize = strong ? '16px' : '14px';
    const weight = strong ? 'bold' : 'normal';
    return `<tr>
        <td style="padding: 5px 12px 5px 0; color: #6F6F6B; font-family: Arial, Helvetica, sans-serif; font-size: ${fontSize}; font-weight: ${weight}; line-height: 20px;">${escapeHtml(label)}</td>
        <td align="right" style="padding: 5px 0; color: ${color}; font-family: Arial, Helvetica, sans-serif; font-size: ${fontSize}; font-weight: ${weight}; line-height: 20px; white-space: nowrap;">${escapeHtml(value)}</td>
    </tr>`;
}

function removePaymentLink(message, paymentLink) {
    let cleaned = String(message || '');
    const link = String(paymentLink || '');
    if (!link) return cleaned;

    const variants = [link];
    try {
        const path = new URL(link).pathname;
        if (path && path !== '/') variants.push(path);
    } catch { /* relative payment links are already covered by `link` */ }

    for (const variant of variants.sort((a, b) => b.length - a.length)) {
        cleaned = cleaned.split(variant).join('');
    }
    return cleaned;
}

/**
 * Invoice-only, email-client-safe document. The caller supplies the already
 * company-scoped invoice model and the canonical payment URL generated by the
 * existing public-link send path.
 */
function buildInvoiceEmailBody({
    message,
    paymentLink,
    includePaymentLink = Boolean(paymentLink),
    invoice,
    companyName,
    timeZone = 'America/New_York',
} = {}) {
    const model = invoice || {};
    const brandName = String(companyName || '').trim() || 'our team';
    const contactName = String(model.contact_name || '').trim();
    const contactFirstName = contactName ? contactName.split(/\s+/)[0] : 'there';
    const invoiceNumber = String(model.invoice_number || '').replace(/^INVOICE\s+/i, '').trim();
    const dueDate = formatDate(model.due_date, timeZone);
    const serviceDate = formatDate(model.service_date, timeZone);
    const serviceAddress = String(model.service_address || '').trim();
    const items = Array.isArray(model.items) ? model.items : [];
    const discount = Number(model.discount_amount || 0);
    const tax = Number(model.tax_amount || 0);
    const amountPaid = Number(model.amount_paid || 0);

    const operatorMessage = (includePaymentLink
        ? String(message || '')
        : removePaymentLink(message, paymentLink)).trim();
    const operatorBlock = operatorMessage ? `<tr>
        <td style="padding: 22px 26px; background-color: #FFFFFF; color: #191919; font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 21px;">${escapeHtml(operatorMessage).replace(/\r\n|\r|\n/g, '<br>')}</td>
    </tr>
    <tr><td height="16" style="height: 16px; font-size: 0; line-height: 0;">&nbsp;</td></tr>` : '';

    const facts = [
        factRow('Amount due', money(model.balance_due)),
        factRow('Due by', dueDate),
        factRow('Service date', serviceDate),
        factRow('Service address', serviceAddress),
    ].join('');

    const itemRows = items.map((item) => {
        const description = String(item?.description || '').trim();
        return `<tr>
            <td style="padding: 14px 0; border-bottom: 1px solid #E6E4E1; vertical-align: top;">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; width: 100%;">
                    <tr>
                        <td style="padding: 0 14px 0 0; color: #191919; font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-weight: bold; line-height: 20px;">${escapeHtml(item?.name || 'Item')}</td>
                        <td align="right" style="padding: 0; color: #191919; font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-weight: bold; line-height: 20px; white-space: nowrap;">${escapeHtml(money(item?.amount))}</td>
                    </tr>
                    ${description ? `<tr><td colspan="2" style="padding: 4px 0 0; color: #6F6F6B; font-family: Arial, Helvetica, sans-serif; font-size: 13px; line-height: 19px;">${escapeHtml(description)}</td></tr>` : ''}
                </table>
            </td>
        </tr>`;
    }).join('');

    const summaryBlock = items.length > 0 ? `<tr>
        <td style="padding: 28px 34px 0;">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; width: 100%;">
                <tr><td style="padding: 0 0 8px; color: #6F6F6B; font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase;">Summary</td></tr>
                ${itemRows}
            </table>
        </td>
    </tr>` : '';

    const totals = [
        totalRow('Subtotal', money(model.subtotal)),
        Number.isFinite(discount) && discount !== 0
            ? totalRow('Discount', `-${money(Math.abs(discount))}`)
            : '',
        Number.isFinite(tax) && tax !== 0 ? totalRow('Tax', money(tax)) : '',
        totalRow('Total', money(model.total), { strong: true }),
        Number.isFinite(amountPaid) && amountPaid > 0
            ? totalRow('Total Paid', money(amountPaid))
            : '',
        totalRow('Total Due', money(model.balance_due), { strong: true, accent: true }),
    ].join('');

    const buttonBlock = includePaymentLink && paymentLink ? `<tr>
        <td align="center" style="padding: 8px 34px 34px;">
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse;">
                <tr>
                    <td align="center" bgcolor="#7F42E1" style="background-color: #7F42E1; border-radius: 6px;">
                        <a href="${escapeHtml(paymentLink)}" style="display: inline-block; padding: 13px 24px; color: #FFFFFF; font-family: Arial, Helvetica, sans-serif; font-size: 15px; font-weight: bold; line-height: 20px; text-decoration: none;">Pay Invoice</a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>` : '';

    const heading = `Your invoice from ${brandName}`;
    const invoiceReference = invoiceNumber ? `Invoice #${invoiceNumber}` : 'your invoice';

    return `<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${escapeHtml(heading)}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #F1F1F0; color: #191919;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; width: 100%; background-color: #F1F1F0;">
        <tr>
            <td align="center" style="padding: 28px 12px;">
                <table role="presentation" width="640" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; width: 100%; max-width: 640px;">
                    ${operatorBlock}
                    <tr>
                        <td style="background-color: #FFFFFF;">
                            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; width: 100%;">
                                <tr>
                                    <td style="padding: 34px 34px 10px; color: #191919; font-family: Arial, Helvetica, sans-serif; font-size: 28px; font-weight: bold; line-height: 35px;">${escapeHtml(heading)}</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px 34px 0; color: #191919; font-family: Arial, Helvetica, sans-serif; font-size: 15px; line-height: 23px;">Hi ${escapeHtml(contactFirstName)},</td>
                                </tr>
                                <tr>
                                    <td style="padding: 10px 34px 0; color: #191919; font-family: Arial, Helvetica, sans-serif; font-size: 15px; line-height: 23px;">Thank you for your recent business with us. Please find a detailed copy of ${escapeHtml(invoiceReference)} below.</td>
                                </tr>
                                <tr>
                                    <td style="padding: 25px 34px 0;">
                                        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; width: 100%; background-color: #F7F7F6;">
                                            <tr><td style="padding: 14px 18px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; width: 100%;">${facts}</table></td></tr>
                                        </table>
                                    </td>
                                </tr>
                                ${summaryBlock}
                                <tr>
                                    <td align="right" style="padding: 24px 34px 20px;">
                                        <table role="presentation" width="300" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; width: 100%; max-width: 300px;">${totals}</table>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding: 10px 34px 22px; color: #191919; font-family: Arial, Helvetica, sans-serif; font-size: 15px; line-height: 23px;">We appreciate your business.</td>
                                </tr>
                                ${buttonBlock}
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>`;
}

module.exports = {
    buildEmailBody,
    buildInvoiceEmailBody,
};
