-- Rollback 144 (ORPHAN-TASK-REHOME-001).
--
-- 144 was a one-time DATA backfill: it moved OPEN tasks' thread_id off hidden
-- shadow orphan timelines onto the surviving contact-linked timeline. The prior
-- thread_id is not recorded anywhere, and the orphans it pointed away from are
-- exactly the rows the Pulse sidebar dedup hides — so there is nothing meaningful
-- to restore. This rollback is a documented no-op; re-applying migration 144 is
-- safe and idempotent.
--
-- To genuinely undo the re-homing you would need a point-in-time restore of the
-- database from before 144 ran — a code/SQL rollback cannot reconstruct the
-- orphan→task mapping.
SELECT 1;
